src/main/java/by/ticket/model/Concert.java
package by.ticket.model;

import java.io.Serializable;
import java.util.List;

/**
 * @author Raman
 * @version 1.0
 * @created 09-Nov-2013 21:46:04
 */
public class Concert implements Serializable {
	private static final long serialVersionUID = -7902601202113763230L;
	
	private String id;
	private String title;
	private String description;
	private String address;
	private List<Performer> performerList;
	private List<Ticket> ticketList;

	public Concert(){
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAddress(){
		return address;
	}

	public void setAddress(String newVal){
		address = newVal;
	}

	public String getDescription(){
		return description;
	}

	public void setDescription(String newVal){
		description = newVal;
	}

	public String getTitle(){
		return title;
	}


	public void setTitle(String newVal){
		title = newVal;
	}
	
	public List<Performer> getPerformerList() {
		return performerList;
	}
	
	public void setPerformerList(List<Performer> performerList) {
		this.performerList = performerList;
	}
	
	public List<Ticket> getTicketList() {
		return ticketList;
	}
	
	public void setTicketList(List<Ticket> ticketList) {
		this.ticketList = ticketList;
	}
}

src/main/java/by/ticket/model/Performer.java
package by.ticket.model;

import java.io.Serializable;


/**
 * @author Raman
 * @version 1.0
 * @created 09-Nov-2013 21:46:04
 */
public class Performer implements Serializable {
	private static final long serialVersionUID = -7791978188890866180L;
	private String id;
	private String title;
	private String description;
	private String style;

	public Performer() {

	}

	public String getDescription(){
		return description;
	}

	public void setDescription(String newVal){
		description = newVal;
	}

	public String getStyle(){
		return style;
	}

	public void setStyle(String newVal){
		style = newVal;
	}

	public String getTitle(){
		return title;
	}

	public void setTitle(String newVal){
		title = newVal;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Override
	public String toString() {
		return title;
	}
}

src/main/java/by/ticket/controller/ConcertController.java
package by.ticket.controller;

import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.primefaces.event.UnselectEvent;

import by.ticket.model.Concert;
import by.ticket.model.Performer;
import by.ticket.service.ConcertService;
import by.ticket.service.PerformerService;



/**
 * @author Raman
 * @version 1.0
 * @created 09-Nov-2013 21:46:22
 */
@ViewScoped
@ManagedBean(name="concertBean")
@SessionScoped
public class ConcertController {
	private Concert concert = new Concert();
	private List<Concert> concerts;
	private String title = "";
	private List<Performer> performers = new ArrayList<>();
    private List<Performer> selectedPerformers = new ArrayList<>();  
    private List<String> selectedTexts = new ArrayList<>();
    
	@ManagedProperty(value = "performerService")
	private PerformerService performerService;
	
	@ManagedProperty(value="#{concertService}")
	private ConcertService concertService;

	public ConcertController(){

	}

	public String searchConcerts(){
		concerts = concertService.searchConcerts(title);
		return "/pages/unsecure/concertsSearch";
	}
	
	public String toAddConcert() {
		this.concert = new Concert();
		selectedPerformers = new ArrayList<>();
		return "/pages/admin/editConcert";
	}
	
	public String toEditConcert(String id) {
		this.concert = concertService.getConcert(id);
		selectedPerformers = concert.getPerformerList();
		return "/pages/admin/editConcert";
	}

	public List<Concert> getConcertList() {
		return concertService.getConcertList();
	}

	public void updateConcert(){

	}
	
	public List<Performer> completePerformer(String titleQuery) {  
        List<Performer> suggestions = performerService.searchPerformers(titleQuery, 10);
        return suggestions;  
    }
	
    public void handleUnselect(UnselectEvent event) {  
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Unselected:" + event.getObject().toString(), null);  
        FacesContext.getCurrentInstance().addMessage(null, message);  
    }

	public void addConcert() {
		concert.setPerformerList(selectedPerformers);
		boolean isSaved = concertService.saveConcert(concert);
		String msg = isSaved ? "Saved!" : "Title is not unique.";
		FacesContext f = FacesContext.getCurrentInstance();
		f.addMessage("messages", new FacesMessage(msg));
	}
	
	public List<Concert> getConcerts() {
		return concerts;
	}

	public void setConcerts(List<Concert> concerts) {
		this.concerts = concerts;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Concert getConcert() {
		return concert;
	}

	public void setConcert(Concert concert) {
		this.concert = concert;
	}
	

	public void setConcertService(ConcertService concertService){
		this.concertService = concertService;
	}

	public List<Performer> getPerformers() {
		return performers;
	}

	public void setPerformers(List<Performer> performers) {
		this.performers = performers;
	}

	public List<Performer> getSelectedPerformers() {
		return selectedPerformers;
	}

	public void setSelectedPerformers(List<Performer> selectedPerformers) {
		this.selectedPerformers = selectedPerformers;
	}

	public List<String> getSelectedTexts() {
		return selectedTexts;
	}

	public void setSelectedTexts(List<String> selectedTexts) {
		this.selectedTexts = selectedTexts;
	}

	public void setPerformerService(PerformerService performerService) {
		this.performerService = performerService;
	}

}

src/main/java/by/ticket/controller/PerformerController.java
package by.ticket.controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import by.ticket.model.Performer;
import by.ticket.service.PerformerService;

/**
 * @author Raman
 * @version 1.0
 * @created 09-Nov-2013 21:46:23
 */
@ManagedBean(name="performerBean")
@SessionScoped
public class PerformerController {
	private Performer performer;

	@ManagedProperty(value="#{performerService}")
	private PerformerService performerService;

	public PerformerController() {

	}
	
	public void addPerformer(){
		boolean isSaved = performerService.savePerformer(performer);
		String msg = isSaved ? "Saved!" : "NOT saved. Title is not unique.";
		FacesContext f = FacesContext.getCurrentInstance();
		f.addMessage("messages", new FacesMessage(msg));
	}

	
	public String toPerformer(String id) {
		performer = performerService.getPerformer(id);
		return "/pages/unsecure/performer";
	}
	
	public String toAddPerformer() {
		performer = new Performer();
		return "/pages/admin/editPerformer";
	}
	
	public String toEditPerformer(String id) {
		performer = performerService.getPerformer(id);
		return "/pages/admin/editPerformer";
	}

	public void setPerformerService(PerformerService performerService){
		this.performerService = performerService;
	}

	public Performer getPerformer(String id) {
		return performerService.getPerformer(id);
	}
	
	public Performer getPerformerByTitle(String title) {
		return performerService.getPerformerByTitle(title);
	}

	public List<Performer> getPerformerList(){
		return performerService.getPerformerList();
	}

	public void updatePerformer(Performer performer){

	}

	public Performer getPerformer() {
		return performer;
	}

	public void setPerformer(Performer performer) {
		this.performer = performer;
	}
}

src/main/webapp/pages/unsecure/about.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
</h:head>
<h:body>
	<ui:composition template="/template/layout/layout.xhtml">
		<ui:define name="content">
			<div id="company-info" class="section selected">
				<h1>What is TicketMaster?</h1>
					<p>A place to buy tickets to your favourite concerts!</p>
			</div>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/unsecure/concerts.xhtml
<ui:composition template="/template/layout/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="content">
			<p:accordionPanel var="concert" value="#{concertBean.concertList}">
				<p:tab title="#{concert.title}" >
					<p>
						<h:outputText value="Address: " style="font-weight:bold" />
						<h:outputText value="#{concert.address}" />
					</p>
					<p>
						<h:outputText value="Performers: " style="font-weight:bold" />
						<ui:repeat var="performer" value="#{concert.performerList}">
							<h:form id="performerForm" >	
								<p:commandLink action="#{performerBean.toPerformer(performer.id)}" value="#{performer.title}" ajax="false"/>
							</h:form>
						</ui:repeat>
					</p>
					<p>
						<h:outputText value="Description: " style="font-weight:bold" />
						<h:outputText value="#{concert.description}" />
					</p>
					<h:form id="editForm" rendered="#{userBean.checkRole('ROLE_ADMIN')}">  
						<p:commandButton value="Edit" action="#{concertBean.toEditConcert(concert.id)}" ajax="false"/>
					</h:form>
				</p:tab>
			</p:accordionPanel>
	</ui:define>
	
	<ui:define name="west">
		<h:form id="searchForm">  	
			<h:panelGrid columns="1">
	            <h:outputLabel for="concertTitle" value="Concert title" />  
	            <p:inputText id="concertTitle" value="#{concertBean.title}" required="true">  
	                <f:validateLength minimum="1" />  
	            </p:inputText>  
	            <p:message for="concertTitle" />  
	            
	            <h:commandButton value="Search" action="#{concertBean.searchConcerts}"   
            		ajax="false" />
	        </h:panelGrid>  
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/pages/unsecure/concertsSearch.xhtml
<ui:composition template="/template/layout/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="content">
			<p:accordionPanel var="concert" value="#{concertBean.concerts}">
				<p:tab title="#{concert.title}">
					<p>
						<h:outputText value="Address: " style="font-weight:bold" />
						<h:outputText value="#{concert.address}" />
					</p>
					<p>
						<h:outputText value="Performers: " style="font-weight:bold" />
						<ui:repeat var="performer" value="#{concert.performerList}">
							<h:form id="performerForm">	
								<p:commandLink action="#{performerBean.toPerformer(performer.id)}" value="#{performer.title}" />
							</h:form>
						</ui:repeat>
					</p>
					<p>
						<h:outputText value="Description: " style="font-weight:bold" />
						<h:outputText value="#{concert.description}" />
					</p>
				</p:tab>
			</p:accordionPanel>
	</ui:define>
	
	<ui:define name="west">
		<h:form id="searchForm">  	
			<h:panelGrid columns="1">
	            <h:outputLabel for="concertTitle" value="Concert title" />  
	            <p:inputText id="concertTitle" value="#{concertBean.title}" required="true">  
	                <f:validateLength minimum="2" />  
	            </p:inputText>  
	            <p:message for="concertTitle" />  
	            
	            <p:commandButton value="Search" actionListener="#{concertBean.searchConcerts}" 
	            	ajax="false" />
	        </h:panelGrid>  
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/pages/unsecure/performer.xhtml
<ui:composition template="/template/layout/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="content">
		<p:accordionPanel>
			<p:tab title="#{performerBean.performer.title}">
				<p>
					<h:outputText value="Style: " style="font-weight:bold"/>
					<h:outputText value="#{performerBean.performer.style}"/>
				</p>
				<p>
					<h:outputText value="Description: " style="font-weight:bold"/>
					<h:outputText value="#{performerBean.performer.description}"/>
				</p>
				<h:form id="editForm" rendered="#{userBean.checkRole('ROLE_ADMIN')}">  
					<p:commandButton value="Edit" action="#{performerBean.toEditPerformer(performerBean.performer.id)}" ajax="false"/>
				</h:form>
			</p:tab>
		</p:accordionPanel>
	</ui:define>
</ui:composition>

src/main/webapp/pages/unsecure/performers.xhtml
<ui:composition template="/template/layout/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="content">
		<p:accordionPanel var="performer" value="#{performerBean.performerList}">
			<p:tab title="#{performer.title}">
				<p>
					<h:outputText value="Style: " style="font-weight:bold"/>
					<h:outputText value="#{performer.style}"/>
				</p>
				<p>
					<h:outputText value="Description: " style="font-weight:bold"/>
					<h:outputText value="#{performer.description}"/>
				</p>
				<h:form id="editForm" rendered="#{userBean.checkRole('ROLE_ADMIN')}">  
					<p:commandButton value="Edit" action="#{performerBean.toEditPerformer(performer.id)}" ajax="false"/>
				</h:form>
			</p:tab>
		</p:accordionPanel>
	</ui:define>
</ui:composition>